
  name: cliffsdelta
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Calculate Cliff's Delta 
  description: |
    A test snap with a simple function.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
